baseURL = "https://blog.zhangsy.me"
languageCode = "en-us"
title = "Siyang's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Siyang"
  homepage = "https://blog.zhangsy.me/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "zsy"
googleAnalytics = "UA-96156731-1"
description = "这里是张思扬的博客，写些心得。更多的是吐槽与无理取闹。"

[[params.socials]]
name = "About"
link = "/about.html"

[[params.socials]]
name = "Github"
link = "https://github.com/Zhang-Siyang"
